routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//  prefix tgat show at url is (adminPnel)
//  prefix tgat show at url is (adminPnel)


//  for language (  package laravel macamara )
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function()
{
	Route::namespace('Front')->name('front.')->group(function()
	{

		Route::get('/','HomeController@index')->name('get.home.index')->middleware('getRoute');
		Route::get('/about','HomeController@about')->name('get.home.about')->middleware('getRoute');

		// contact us page
		Route::get('/contact-us','ContactUsController@contact')->name('get.contactus.contact')->middleware('getRoute');
		// gallery page
		Route::get('/gallery','ContactUsController@gallery')->name('get.contactus.gallery')->middleware('getRoute');

		// portfolio page
		// Route::get('/portfolio','PortfolioController@portfolio')->name('get.portfolio.index')->middleware('getRoute');


		// services 
		Route::get('/services','ServiceController@all')->name('get.service.all')->middleware('getRoute');
		// show services according to category
		Route::get('/service/{slugCat}','ServiceController@category')->name('get.service.category')->middleware('getRoute');
		// show one service
		Route::get('/services/{slugService}','ServiceController@show')->name('get.service.show')->middleware('getRoute');
		// order this service
		// Route::post('/order','ServiceController@order')->name('post.service.order');


		// Blog 
		Route::get('/blog','BlogController@index')->name('get.blog.index')->middleware('getRoute');
		Route::get('/blog/{slugBlog}','BlogController@show')->name('get.blog.show')->middleware('getRoute');



		// subscribe
		Route::post('/subscribe','ContactUsController@subscribe')->name('post.contactus.subscribe')->middleware('postRoute');
		// send message from contact us page 
		Route::post('/send-message','ContactUsController@sendMessage')->name('post.contactus.sendMessage')->middleware('getRoute');

	});


});

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = ['name','category_id','language_id','img','small_description','description','slug','show_in_homePage'];
    public function category()
    {
    	return $this->hasOne('App\Models\Category','id','category_id');
    }


    public function images()
    {
    	return $this->hasMany('App\Models\ServiceImage','service_id','id');
    }
}

app/Http/Controllers/Admin/Service/ImageController.php
<?php

namespace App\Http\Controllers\Admin\Service;

use Illuminate\Http\Request;
use App\Http\Requests\CustomerRequest;
use App\Http\Controllers\Controller;
use App\Models\Service;
use App\Models\ServiceImage ;

use Image;
use Storage;


class ImageController extends Controller
{
   

   // return view of seo data 
    public function addImages($id)
    {
        $data ['service'] = Service::findOrFail($id);
        $data['images'] = ServiceImage::where('service_id',$id)->get();
        return view('admin.service.images.index')->with($data);

    }



     // storing data in db 
    public function moreImages(Request $request)
    {
        $this->validate($request, [

                'id'   => 'required|numeric|exists:services,id',
                'img'   => 'required',
                'img.*' => 'image|mimes:jpeg,png,jpg,gif,svg|max:100000'

        ]);

         if($request->hasfile('img'))
         {
            foreach($request->file('img') as $image)
            { 
                $data = new ServiceImage();

                // upload image using intervention without resizeing
                $img = Image::make($image);
                // save image
                $img->save(UPLOADS_PATH.SERVICE_IMAGES_PATH.$image->hashName());

                $data->service_id = $request->id;
                $data->img = $image->hashName();
                $data->save();

            }
         }
        session()->flash('message',trans('site.added_success'));
        return back();
    }




    public function deleteImage($id)
    {
        $data = ServiceImage::findOrFail($id);
        Storage::disk('public_uploads')->delete(SERVICE_IMAGES_PATH.$data->img);
        ServiceImage::destroy($id);
        session()->flash('message',trans('site.deleted_success'));
        return back();


    }








}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\ServiceRequest;
use App\Http\Controllers\Controller;
use App\Models\Service;
use App\Models\Category;


use Image;
use Storage;
use App\Helpers\Classes\UploadClass;

class ServiceController extends Controller
{



    public function index()
    {
    	$data['services'] = Service::select('id','name','language_id','status','sort','category_id')
    	->where('language_id',language())
    	->orderBy('sort')
    	->paginate(30);
    	return view('admin.service.index')->with($data);
    }



    // return view of adding data 
    public function add()
    {
        $data['categories'] = Category::select('id','name','language_id')
        ->where('language_id',adminAuth()->user()->language_id)
        ->orderBy('sort')
        ->get();
    	return view('admin.service.add')->with($data);
    }





    // storing data in db 
    public function store(ServiceRequest $request)
    {
    	$data = $request->validated();
    	$data['language_id'] = language();

        // upload image of this module
        if($request->hasFile('img'))
        {
            // UPLOADS_PATH.CATEGORY_PATH 
            // -> static path ( you can change it from helpers/files/basehelper)
            $img = UploadClass::uploadImage($request,'img',UPLOADS_PATH.SERVICE_PATH,$all=true);
            $data['img'] = $img;
        }
        //  slug
        if($request->slug != ''){$data['slug'] = slug($request->slug);}
        else{$data['slug'] = slug($request->name).uniqid();}
    	Service::create($data); // inserting data 
    	session()->flash('message',trans('site.added_success'));
    	return redirect(route('admin.get.service.index'));
    }







    // return view of editing data 
    public function edit($id)
    {
        $data['categories'] = Category::select('id','name','language_id')
        ->where('language_id',adminAuth()->user()->language_id)
        ->orderBy('sort')
        ->get();
    	$data['row'] = Service::findOrFail($id);
    	return view('admin.service.edit')->with($data);
    }



    // storing data in db 
    public function update(ServiceRequest $request)
    {
    	$data = $request->validated();

        // upload image of this module
        if($request->hasFile('img'))
        {
            $old = Service::findOrFail($request->id);
            // delete old image from server
            if($old->img)
            {
                Storage::disk('public_uploads')->delete(SERVICE_PATH.$old->img);
                Storage::disk('public_uploads')->delete(SERVICE_PATH.'small/'.$old->img);
                Storage::disk('public_uploads')->delete(SERVICE_PATH.'medium/'.$old->img);
            }
            // UPLOADS_PATH.CATEGORY_PATH 
            // -> static path ( you can change it from helpers/files/basehelper)
            $img = UploadClass::uploadImage($request,'img',UPLOADS_PATH.SERVICE_PATH,$all=true);
            $data['img'] = $img;
        }
        //  slug
        if($request->slug != ''){$data['slug'] = slug($request->slug);}
        else{$data['slug'] = slug($request->name).uniqid();}
    	// updating data in db
    	Service::where('id', $request->id)->update($data);
    	session()->flash('message',trans('site.updated_success'));
    	return redirect(route('admin.get.service.index'));
    }



















    // deleteing row from db  ( soft delete )
    public function delete($id)
    {

    	$old = Service::findOrFail($id);

        Storage::disk('public_uploads')->delete(SERVICE_PATH.$old->img);
        Storage::disk('public_uploads')->delete(SERVICE_PATH.'small/'.$old->img);
        Storage::disk('public_uploads')->delete(SERVICE_PATH.'medium/'.$old->img);


    	Service::findOrFail($id)->delete();
    	session()->flash('message',trans('site.deleted_success'));
    	return back();

    }

    // delete mutli row from table 
    public function deleteMulti(Request $request)
    {
    	foreach ($request->deleteMulti as  $value) 
    	{

            $old = Service::findOrFail($value);
            Storage::disk('public_uploads')->delete(SERVICE_PATH.$old->img);
            Storage::disk('public_uploads')->delete(SERVICE_PATH.'small/'.$old->img);
            Storage::disk('public_uploads')->delete(SERVICE_PATH.'medium/'.$old->img);
    		Service::findOrFail($value)->delete();
	    	
    	}

    	session()->flash('message',trans('site.deleted_success'));
	    return back();
    }


     // delete mutli row from table 
    public function sort(Request $request)
    {
    	$i = 1;
    	foreach ($request->sort as  $value) 
    	{
    		$data = Service::find($value);
    		$data->sort = $i;
    		$data->save();
    		$i++;
    	}
    	session()->flash('message',trans('site.sorted_success'));
	    return back();
    }






    // visibility  for this item ( active or not active  -- change status of this item )
    public function visibility($id)
    {
    	$data = Service::findOrFail($id);

    	switch ($data->status) 
    	{
    		case 'yes':
    			$data->status = 'no';
    			$data->save();
    			session()->flash('message',trans('site.deactivate_message'));
    			break;

    		case 'no':
    			$data->status = 'yes';
    			session()->flash('message',trans('site.activate_message'));
    			$data->save();
    			break;
    		
    		default:
    			# code...
    			break;
    	}

    	return back();

    }















   // return view of seo data 
    public function seo($id)
    {
        $data['seo'] = Service::where('language_id',language())->findOrFail($id);
        $data['seoData'] = json_decode($data['seo']['seo']);
        return view('admin.service.seo')->with($data);

    }



     // storing data in db 
    public function updateSeo(Request $request)
    {
        $data = $request->except('id','_token');
        // updating data in db
        $seoData = Service::find($request->id);
        $seoData->seo = json_encode($data);
        $seoData->save();
        session()->flash('message',trans('site.updated_success'));
        return back();
    }











}

app/Http/Controllers/Front/BlogController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Blog;


class BlogController extends Controller
{
    
    // base function for admin 
    public function index()
    {
        $data['posts'] = Blog::select('name','slug','small_description','img','created_at')
        ->where('status','yes')
        ->where('language_id',lang_front())->paginate(6);

        $data['latest'] = Blog::select('name','slug')
        ->where('language_id',lang_front())->latest()->take(6)->get();

        return view('front.blog.index')->with($data);
    }




    // view data of specific service 
    public function show($slugBlog)
    {
        $check = Blog::where('language_id',lang_front())
        ->where('status','yes')->where('slug',$slugBlog)->first();
        if($check)
        {
            $data['latest'] = Blog::select('name','slug')->where('status','yes')
            ->where('language_id',lang_front())->latest()->take(6)->get();
            $data['row'] = $check;
            return view('front.blog.show')->with($data);
        }
    }

}

app/Http/Controllers/Front/ContactUsController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Newsletter;
use App\Models\Message;


use App\Models\Category;
use App\Models\Brand;
use App\Models\SubCategory;


class ContactUsController extends Controller
{
    


    public function contact()
    {
    	return view('front.static.contact');
    }


    // send message   
    public function sendMessage(Request $request)
    {

        if($request->ajax())
        {
            $request->validate([

                'name' => 'required|string|max:100',
                'phone' => 'required|numeric|digits_between:6,15',
                'email' => 'required|email|max:100',
                'message' => 'required|string|max:2000',
            ]);

            $data = $request->except("_token");

            Message::create($data);
            $message['success'] = trans('frontSite.contactusMessage');
            return response()->json($message);
        }
    }





    //  gallery
    public function gallery()
    {
    	return view('front.static.gallery');
    }




    public function subscribe(Request $request)
    {

        $request->validate(['email'=> 'required|email|unique:newsletters,email']);
        $data = new Newsletter();
        $data->email = $request->email;
        $data->save();
        session()->flash('message',trans('frontSite.subscribeMessage'));
        return back();
    }






}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Slider;
use App\Models\Category;


class HomeController extends Controller
{
    
    // base function for admin 
    public function index()
    {
        $data['slider'] = Slider::select('name','description','img','link')
        ->where('status','yes')
        ->where('language_id',lang_front())->take(3)->get();
        
        return view('front.index')->with($data);
    }



    // base function for admin 
    public function about()
    {
        
        return view('front.static.about');
    }

}

app/Http/Controllers/Front/ServiceController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Service;


class ServiceController extends Controller
{
    
    // base function for admin 
    public function all()
    {
        $data['categories'] = Category::where('language_id',lang_front())->where('status','yes')->get();
        return view('front.services.index')->with($data);
    }


    // view data of specific service 
    public function category($slugcat)
    {
        $check = Category::where('language_id',lang_front())->where('slug',$slugcat)
        ->where('status','yes')->first();
        if($check)
        {
            $data['row'] = $check;
            $data['catService'] = Service::where('category_id',$check->id)
            ->where('status','yes')->paginate(15);
            return view('front.services.category')->with($data);
        }
    }


    // view data of specific service 
    public function show($slugService)
    {
        $check = Service::where('language_id',lang_front())
        ->where('status','yes')->where('slug',$slugService)->first();
        if($check)
        {
            $data['row'] = $check;
            return view('front.services.show')->with($data);
        }
    }

}

resources/views/front/services/category.blade.php
@extends('front.main')


@section('content')


<!-- page-title-section start -->
<section class="title-hero-bg blog-cover-bg" data-stellar-background-ratio="0.2">
  <div class="container">
    <div class="page-title text-center">
      <h1> {{$row->name}}  </h1>
    </div>
  </div>
</section>
<!-- page-title-section end --> 

<!------ Blogs Start ------>
<section class="pt-100 pb-100">
  <div class="container">

    <div class="row mt-50">

        @foreach($catService as $ser)
        <div class="col-md-4">
            <div class="post">
            <div class="post-img"> 
                <a href="{{route('front.get.service.show',[$ser->slug])}}" > 
                <img class="img-responsive" src="{{getImage(SERVICE_PATH.'small/'.$ser->img)}}" alt=""/> 
                </a>
            </div>
            <div class="post-info">
                <h3><a href="{{route('front.get.service.show',[$ser->slug])}}"> {{\Str::Words($ser->name,'4','..')}} </a></h3>
                <p> {{\Str::Words($ser->small_description,'20','...')}} </p>
                <a class="readmore dark-color" href="{{route('front.get.service.show',[$ser->slug])}}">
                    <span>@lang('frontSite.viewMore')</span>
                </a> 
                </div>
            </div>
        </div>
        @endforeach
      <!-- Post End -->
      
    </div>
  </div>
</section>
<!------ Blogs End ------> 






@endsection

resources/views/front/services/index.blade.php
@extends('front.main')


@section('content')


<!-- page-title-section start -->
<section class="title-hero-bg portfolio-cover-bg" data-stellar-background-ratio="0.2">
	<div class="container">
    	<div class="page-title text-center">
        	<h1> {{ json_data($site_content,'sectionLinks_services') }} </h1>
        </div>
	</div>
</section>
<!-- page-title-section end -->
        
<!------ Portfolio Start ------>
<section class="pt-100 pt-100">
  <div class="container">
    <div class="row">
      <div class="portfolio-container text-center">
        <ul id="portfolio-filter" class="list-inline filter-transparent">
          <li class="active" data-group="all">All</li>
          @foreach($categories as $cat)
          <li data-group="{{$cat->slug}}">{{$cat->name}}</li>
          @endforeach
        </ul>
        <ul id="portfolio-grid" class="four-column hover-two">


        @foreach($services as $ser)

          <li class="portfolio-item gutter-space" data-groups='["all", "{{$ser->category->slug}}"]'>
            <div class="portfolio">
              <div class="dark-overlay"></div>
              <img src="{{getImage(SERVICE_PATH.'small/'.$ser->img)}}" alt="">
              <div class="portfolio-wrap">
                <div class="portfolio-description">
                  <h3 class="portfolio-title">{{\Str::Words($ser->name,'3','..')}}</h3>
                  <a href="{{route('front.get.service.category',[$ser->category->slug])}}" class="links">
                    {{\Str::Words($ser->category->name,'3','..')}}
                  </a> 
                </div>
                <!-- /.project-info -->
                
                <ul class="portfolio-details">
                  <li><a class="alpha-lightbox" href="{{getImage(SERVICE_PATH.'medium/'.$ser->img)}}" ><i class="fa fa-search"></i></a></li>
                  <li><a href="{{route('front.get.service.show',[$ser->slug])}}"><i class="fa fa-link"></i></a></li>
                </ul>
              </div>
            </div>
            <!-- /.portfolio --> 
          </li>

        @endforeach

         
        </ul>
      </div>
    </div>
    <div class="row mt-100">
    	<p class="text-center">
            <a class="btn btn-color btn-circle" href="{{route('front.get.contactus.contact')}}">@lang('frontSite.startService')</a>
        </p>
    </div>
  </div>
</section>
<!------ Portfolio End ------> 





@endsection

resources/views/front/services/show.blade.php
@extends('front.main')


@section('content')

<!-- page-title-section start -->
<section class="title-hero-bg portfolio-cover-bg" data-stellar-background-ratio="0.2">
	<div class="container">
    	<div class="page-title text-center">
        	<h1>  {{$row->name}} </h1>
        </div>
	</div>
</section>
<!-- page-title-section end -->
        
<!------ Portfolio Start ------>
<section class="pt-100 pt-100">
  <div class="container">
    <div class="row">
		<div class="col-md-12 portfolio-left">
        	<div class="portfolio-slider owl-carousel">
                <div class="item text-center"><img  src="{{getImage(SERVICE_PATH.$row->img)}}" alt="{{$row->name}}"/></div>
                @foreach($row->images as $img)
                <div class="item"><img class="img-responsive" src="{{getImage(SERVICE_IMAGES_PATH.$img->img)}}" alt="{{$row->name}}"/></div>
                @endforeach
            </div>
            <h3>@lang('frontSite.serviceDetails')</h3>
            <p class="mt-20">{!! $row->description !!}</p>
            <p class="mt-50"><a class="btn btn-color btn-circle" href="{{route('front.get.contactus.contact')}}" >@lang('frontSite.startService')</a></p>
        </div>
        <!-- Left Side End -->
    </div>
  </div>
</section>
<!------ Portfolio End ------> 


@endsection